// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(CaraxEntitiy))]
    [Migration("20190604184228_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Company", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxNo")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("VisualId");

                    b.HasKey("Code");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Models.Customers.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<DateTime?>("BirthOfDateTime");

                    b.Property<string>("CompanyCode");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("DepartmentCode");

                    b.Property<string>("EMail");

                    b.Property<string>("FirstPhone");

                    b.Property<int>("Gender");

                    b.Property<bool>("InBlackList");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.Property<string>("Nationality");

                    b.Property<string>("PassportSerialNumber");

                    b.Property<string>("SecondPhone");

                    b.Property<string>("SerialNumberOfDrivingLicense");

                    b.Property<string>("Surname");

                    b.Property<string>("Tc");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDateTime");

                    b.Property<int>("YearOfDrivingLicense");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("DepartmentCode");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Models.Department", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("VisualId");

                    b.HasKey("Code");

                    b.HasIndex("CompanyCode");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Models.Tokens.Token", b =>
                {
                    b.Property<Guid>("TokenGuid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TokenEndDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TokenGuid");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("DepartmentCode");

                    b.HasIndex("UserId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("binary(64)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("binary(64)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("UserLevel")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VisualId");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("DepartmentCode");

                    b.HasIndex("VisualId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Models.Users.UserDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyCode");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("DepartmentCode");

                    b.HasIndex("UserId");

                    b.ToTable("UserDepartments");
                });

            modelBuilder.Entity("Models.Users.UserTokenInfo", b =>
                {
                    b.Property<Guid>("TokenGuid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("TokenEndDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId");

                    b.Property<int>("UserLevel")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TokenGuid");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("DepartmentCode");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokenInfos");
                });

            modelBuilder.Entity("Models.Visual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<byte[]>("Data");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDateTime");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("DepartmentCode");

                    b.ToTable("Visuals");
                });

            modelBuilder.Entity("Models.Customers.Customer", b =>
                {
                    b.HasOne("Models.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyCode");

                    b.HasOne("Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentCode");
                });

            modelBuilder.Entity("Models.Department", b =>
                {
                    b.HasOne("Models.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyCode");
                });

            modelBuilder.Entity("Models.Tokens.Token", b =>
                {
                    b.HasOne("Models.Company", "Company")
                        .WithMany("Tokens")
                        .HasForeignKey("CompanyCode");

                    b.HasOne("Models.Department", "Department")
                        .WithMany("Tokens")
                        .HasForeignKey("DepartmentCode");

                    b.HasOne("Models.Users.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Models.Users.User", b =>
                {
                    b.HasOne("Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyCode");

                    b.HasOne("Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentCode");

                    b.HasOne("Models.Visual", "Visual")
                        .WithMany("Users")
                        .HasForeignKey("VisualId");
                });

            modelBuilder.Entity("Models.Users.UserDepartment", b =>
                {
                    b.HasOne("Models.Company", "Company")
                        .WithMany("UserDepartments")
                        .HasForeignKey("CompanyCode");

                    b.HasOne("Models.Department", "Department")
                        .WithMany("UserDepartments")
                        .HasForeignKey("DepartmentCode");

                    b.HasOne("Models.Users.User", "User")
                        .WithMany("UserDepartments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Models.Users.UserTokenInfo", b =>
                {
                    b.HasOne("Models.Company", "Company")
                        .WithMany("UserTokenInfo")
                        .HasForeignKey("CompanyCode");

                    b.HasOne("Models.Department", "Department")
                        .WithMany("UserTokenInfo")
                        .HasForeignKey("DepartmentCode");

                    b.HasOne("Models.Users.User", "User")
                        .WithMany("UserTokenInfos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Models.Visual", b =>
                {
                    b.HasOne("Models.Company", "Company")
                        .WithMany("Visuals")
                        .HasForeignKey("CompanyCode");

                    b.HasOne("Models.Department", "Department")
                        .WithMany("Visuals")
                        .HasForeignKey("DepartmentCode");
                });
#pragma warning restore 612, 618
        }
    }
}
