// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Services.Migrations
{
    [DbContext(typeof(CaraxEntitiy))]
    [Migration("20190704183955_pre0.6")]
    partial class pre06
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Cars.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(35)");

                    b.Property<int?>("VisualId");

                    b.HasKey("Id");

                    b.HasIndex("VisualId");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Models.Cars.BrandModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BrandId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VisualId");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("VisualId");

                    b.ToTable("BrandModels");
                });

            modelBuilder.Entity("Models.Cars.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId");

                    b.Property<int>("BrandModelId");

                    b.Property<int>("CaseType");

                    b.Property<int?>("Classes");

                    b.Property<string>("Color");

                    b.Property<string>("CompanyCode");

                    b.Property<bool>("Crash");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("DepartmentCode");

                    b.Property<decimal?>("Deposit");

                    b.Property<string>("EngineCapacity");

                    b.Property<int>("FuelType");

                    b.Property<int>("GearType");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Km");

                    b.Property<bool>("Maintenance");

                    b.Property<int>("MinDriverLicense");

                    b.Property<string>("Name");

                    b.Property<int>("NumberOfDoors");

                    b.Property<string>("Plate")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDateTime");

                    b.Property<int?>("VisualId");

                    b.Property<string>("Year");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("BrandModelId");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("DepartmentCode");

                    b.HasIndex("VisualId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Models.Cars.CarInService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarId");

                    b.Property<int>("CarServiceId");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("CarServiceId");

                    b.ToTable("CarInServices");
                });

            modelBuilder.Entity("Models.Cars.CarProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("Name");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDateTime");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarProperties");
                });

            modelBuilder.Entity("Models.Cars.CarService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyCode");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("DepartmentCode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 64)))
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDateTime");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("DepartmentCode");

                    b.ToTable("CarServices");
                });

            modelBuilder.Entity("Models.Company", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxNo")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("VisualId");

                    b.HasKey("Code");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Models.Customers.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("BirthOfDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CompanyCode");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("DepartmentCode");

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FirstPhone")
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("Gender");

                    b.Property<bool>("InBlackList");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PassportSerialNumber")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecondPhone")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SerialNumberOfDrivingLicense")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tc")
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDateTime");

                    b.Property<DateTime>("YearOfDrivingLicense");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("DepartmentCode");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Models.Department", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("VisualId");

                    b.HasKey("Code");

                    b.HasIndex("CompanyCode");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Models.Reservations.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BeginDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("CarId");

                    b.Property<string>("CompanyCode");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<int>("CustomerId");

                    b.Property<string>("DeliveryLocation")
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("DepartmentCode");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsApproval");

                    b.Property<bool>("IsDeleted");

                    b.Property<decimal?>("Price");

                    b.Property<int>("ReservationStatus");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDateTime");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DepartmentCode");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Models.Reservations.ServicesInReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarSericeId");

                    b.Property<string>("CompanyCode");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("DepartmentCode");

                    b.Property<int>("ReservationId");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDateTime");

                    b.HasKey("Id");

                    b.HasIndex("CarSericeId");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("DepartmentCode");

                    b.HasIndex("ReservationId");

                    b.ToTable("ServicesInReservations");
                });

            modelBuilder.Entity("Models.Tokens.Token", b =>
                {
                    b.Property<Guid>("TokenGuid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TokenEndDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TokenGuid");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("DepartmentCode");

                    b.HasIndex("UserId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("binary(64)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("binary(64)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("UserLevel")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VisualId");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("DepartmentCode");

                    b.HasIndex("VisualId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Models.Users.UserDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyCode");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("DepartmentCode");

                    b.HasIndex("UserId");

                    b.ToTable("UserDepartments");
                });

            modelBuilder.Entity("Models.Users.UserTokenInfo", b =>
                {
                    b.Property<Guid>("TokenGuid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("TokenEndDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId");

                    b.Property<int>("UserLevel")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TokenGuid");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("DepartmentCode");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokenInfos");
                });

            modelBuilder.Entity("Models.Visual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<byte[]>("Data");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDateTime");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("DepartmentCode");

                    b.ToTable("Visuals");
                });

            modelBuilder.Entity("Models.Cars.Brand", b =>
                {
                    b.HasOne("Models.Visual", "Visual")
                        .WithMany("Brands")
                        .HasForeignKey("VisualId");
                });

            modelBuilder.Entity("Models.Cars.BrandModel", b =>
                {
                    b.HasOne("Models.Cars.Brand", "Brand")
                        .WithMany("BrandModels")
                        .HasForeignKey("BrandId");

                    b.HasOne("Models.Visual", "Visual")
                        .WithMany("BrandModels")
                        .HasForeignKey("VisualId");
                });

            modelBuilder.Entity("Models.Cars.Car", b =>
                {
                    b.HasOne("Models.Cars.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Models.Cars.BrandModel", "BrandModel")
                        .WithMany("Cars")
                        .HasForeignKey("BrandModelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Models.Company", "Company")
                        .WithMany("Cars")
                        .HasForeignKey("CompanyCode");

                    b.HasOne("Models.Department", "Department")
                        .WithMany("Cars")
                        .HasForeignKey("DepartmentCode");

                    b.HasOne("Models.Visual", "Visual")
                        .WithMany("Cars")
                        .HasForeignKey("VisualId");
                });

            modelBuilder.Entity("Models.Cars.CarInService", b =>
                {
                    b.HasOne("Models.Cars.Car", "Car")
                        .WithMany("CarInServices")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Models.Cars.CarService", "CarService")
                        .WithMany("CarInServices")
                        .HasForeignKey("CarServiceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Models.Cars.CarProperty", b =>
                {
                    b.HasOne("Models.Cars.Car", "Car")
                        .WithMany("CarProperties")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Models.Cars.CarService", b =>
                {
                    b.HasOne("Models.Company", "Company")
                        .WithMany("CarServices")
                        .HasForeignKey("CompanyCode");

                    b.HasOne("Models.Department", "Department")
                        .WithMany("CarServices")
                        .HasForeignKey("DepartmentCode");
                });

            modelBuilder.Entity("Models.Customers.Customer", b =>
                {
                    b.HasOne("Models.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyCode");

                    b.HasOne("Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentCode");
                });

            modelBuilder.Entity("Models.Department", b =>
                {
                    b.HasOne("Models.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyCode");
                });

            modelBuilder.Entity("Models.Reservations.Reservation", b =>
                {
                    b.HasOne("Models.Cars.Car", "Car")
                        .WithMany("Reservations")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Models.Company", "Company")
                        .WithMany("Reservations")
                        .HasForeignKey("CompanyCode");

                    b.HasOne("Models.Customers.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Models.Department", "Department")
                        .WithMany("Reservations")
                        .HasForeignKey("DepartmentCode");
                });

            modelBuilder.Entity("Models.Reservations.ServicesInReservation", b =>
                {
                    b.HasOne("Models.Cars.CarService", "CarService")
                        .WithMany("ServicesInReservations")
                        .HasForeignKey("CarSericeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Models.Company", "Company")
                        .WithMany("ServicesInReservations")
                        .HasForeignKey("CompanyCode");

                    b.HasOne("Models.Department", "Department")
                        .WithMany("ServicesInReservations")
                        .HasForeignKey("DepartmentCode");

                    b.HasOne("Models.Reservations.Reservation", "Reservation")
                        .WithMany("ServicesInReservations")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Models.Tokens.Token", b =>
                {
                    b.HasOne("Models.Company", "Company")
                        .WithMany("Tokens")
                        .HasForeignKey("CompanyCode");

                    b.HasOne("Models.Department", "Department")
                        .WithMany("Tokens")
                        .HasForeignKey("DepartmentCode");

                    b.HasOne("Models.Users.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Models.Users.User", b =>
                {
                    b.HasOne("Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyCode");

                    b.HasOne("Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentCode");

                    b.HasOne("Models.Visual", "Visual")
                        .WithMany("Users")
                        .HasForeignKey("VisualId");
                });

            modelBuilder.Entity("Models.Users.UserDepartment", b =>
                {
                    b.HasOne("Models.Company", "Company")
                        .WithMany("UserDepartments")
                        .HasForeignKey("CompanyCode");

                    b.HasOne("Models.Department", "Department")
                        .WithMany("UserDepartments")
                        .HasForeignKey("DepartmentCode");

                    b.HasOne("Models.Users.User", "User")
                        .WithMany("UserDepartments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Models.Users.UserTokenInfo", b =>
                {
                    b.HasOne("Models.Company", "Company")
                        .WithMany("UserTokenInfo")
                        .HasForeignKey("CompanyCode");

                    b.HasOne("Models.Department", "Department")
                        .WithMany("UserTokenInfo")
                        .HasForeignKey("DepartmentCode");

                    b.HasOne("Models.Users.User", "User")
                        .WithMany("UserTokenInfos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Models.Visual", b =>
                {
                    b.HasOne("Models.Company", "Company")
                        .WithMany("Visuals")
                        .HasForeignKey("CompanyCode");

                    b.HasOne("Models.Department", "Department")
                        .WithMany("Visuals")
                        .HasForeignKey("DepartmentCode");
                });
#pragma warning restore 612, 618
        }
    }
}
