//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTokenInfo
    {
        public System.Guid TokenGuid { get; set; }
        public System.DateTime TokenEndDateTime { get; set; }
        public int UserId { get; set; }
        public string Username { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string DepartmentCode { get; set; }
        public string CompanyCode { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
        public virtual User User { get; set; }
    }
}
